import Head from 'next/head';

import Hero from './Hero';
import Section2 from './section1';

const Home = () => {
	return (
		<main className='main'>
			<Head>
				<title>KOMBUCHA</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
      
			<Hero />
			<Section2 />
		</main>
	);
};

export default Home;
