import Head from 'next/head';

import Hero from './Hero';
import Section1 from './Section1';
import Section2 from './Section2';
import Section3 from './Section3';

const Home = () => {
	return (
		<main className='main'>
			<Head>
				<title>KOMBUCHA</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Hero />
			<Section1 />
			<Section2 />
			<Section3 />
		</main>
	);
};

export default Home;
