const UdemyContent = {
	types: ['normal-content-section'],
	name: 'Udemy',
	info: '',
	classes: 'main-section Site',
	list: [],
};

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: '10 Mega Responsive Websites With HTML, CSS, And JavaScript',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project'],
			name: 'Foods',
			info: 'Foods',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: '50 Projects In 50 Days - HTML, CSS And JavaScript',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project'],
			name: 'Expanding Cards',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Progress Steps',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: 'Complete React Developer in 2021 with (Redux, Hooks, GraphQL)',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project', 'extra-url-after-name'],
			extraUrlAfterName: 'client/build',
			name: 'CRW Clothing (E-Commerce Project)',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript', 'Firebase'],
				libraries: ['React'],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project', 'extra-url-after-name'],
			extraUrlAfterName: 'build',
			name: 'monsters-rolodex',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: ['React'],
				frameworks: [],
				APIs: [
					'https://jsonplaceholder.typicode.com/',
					'https://robohash.org/',
				],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: 'Monster JavaScript Course - 50+ projects and applications',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project'],
			name: 'Accordion Component',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Alien Invader Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Audio Button Player',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Background Color & Font Color Divs Buttons Changer',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Background Color & Font Color Divs Buttons Changer2',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Background Color Body Buttons Changer',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Building A Flying Bird Game From Scratch',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Calculator Mini Web Application',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Car Driving Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Card War Project',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Catch Element Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Click Popper Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Click Reaction Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Clipboard - Copy And Move Text',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Coin Toss Game Code',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Combination Guessr Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Countdown Timer',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Create Form Validation Using JavaScript',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Creating A Tooltip Popup With JavaScript',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Creating An Image Popup Window On Image Elements',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Current Date(Eastern European Standard Time)',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Document Object Model',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Document Object Model Element Manipulation With JS',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Dom Content Loaded',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Dynamic Editable Shopping List',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'DOM Interaction Application DOMinator',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Dynamic welcome message',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Element Catcher Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Element Mouse And Click Events',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Element Scrolling Content',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Email Extractor Application',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name:
				'Explore JavaScript Cookies While Building Cookie Get Set Tester Web Application',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'From Ten To Zero',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Functionator JavaScript Function practice Code',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Guess The Hidden Word Which Is Scrambled',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'High Low Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Image Carousel Animated Slideshow Application',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Input Field Character Counter',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name:
				'JavaScript Application To Create Files - Google Sheet Data To CSV File',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Just JavaScript Click Counter',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Keyboard Div Mover',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Keyboard Events Tracker',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Magic Eight Ball',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Modal Popup Example',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Number Guessing Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Pattern Matching Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Placeholder Image Path Generator',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Plane Bomber Game Simple JavaScript DOM Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Popup Message',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Random Array Message',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Random Background Color Button Generator',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Rock Paper Scissors Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Simple List',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['deep-list-content-files'],
			name: 'Some Js Code',
			info: '',
			list: [
				{
					types: ['normal-deep-list-content-files-item'],
					title: 'Bubbling & Capturing',
					info: '',
					filename: 'index',
					fileExtension: 'html',
					tech: {
						languages: ['HTML', 'CSS', 'JavaScript'],
						libraries: [],
						frameworks: [],
						APIs: [],
					},
				},
				{
					types: ['normal-deep-list-content-files-item'],
					title:
						"Generating A Random Numbers In A Range That Doesn't Exist In From an Array",
					info: '',
					filename: 'app',
					fileExtension: 'js',
					tech: {
						languages: ['HTML', 'CSS', 'JavaScript'],
						libraries: [],
						frameworks: [],
						APIs: [],
					},
				},
				{
					types: ['normal-deep-list-content-files-item'],
					title: 'JS Local Strorage',
					info: '',
					filename: 'index',
					fileExtension: 'html',
					tech: {
						languages: ['HTML', 'CSS', 'JavaScript'],
						libraries: [],
						frameworks: [],
						APIs: [],
					},
				},
				{
					types: ['normal-deep-list-content-files-item'],
					title: 'ProtoType in JS',
					info: '',
					filename: 'app',
					fileExtension: 'js',
					tech: {
						languages: ['HTML', 'CSS', 'JavaScript'],
						libraries: [],
						frameworks: [],
						APIs: [],
					},
				},
				{
					types: ['no-deep-list-content-files-item'],
					title: '',
					info: '',
					filename: 'app',
					fileExtension: 'js',
					tech: {
						languages: ['HTML', 'CSS', 'JavaScript'],
						libraries: [],
						frameworks: [],
						APIs: [],
					},
				},

				// Deep Inner List End
			],
		},
		{
			types: ['normal-content-project'],
			name: 'Some Mouse Events',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Star Rating Project Click And Hover Events',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Tip Calculater',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Try & Catch',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Typing Test Mini Application',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Ultimate Dice Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Word Guessing Hangman Game',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Word Scrumble',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'xHR & Fetch',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['no-content-course'],
	name: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: 'The Modern Javascript Bootcamp Course (2020)',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project'],
			name: 'Coin Chaser',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Maze',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Movies Fight',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Practicing Promise, Async& Await',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Practicing Prototypes, Classes, & The New Operator',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Secret Message Sharing App',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Timer',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['normal-content-course'],
	name: 'The Complete Web Developer in 2021 Zero to Mastery',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['normal-content-project'],
			name: 'bootStrap-mini-project',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Gradiant Background',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Only HTML Website',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Playing With Grid',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project', 'extra-url-after-name'],
			extraUrlAfterName: 'build',
			name: 'robofriends',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: ['tachyon'],
				frameworks: ['react'],
				APIs: ['https://jsonplaceholder.typicode.com/users'],
			},
		},
		{
			types: ['normal-content-project'],
			name: 'Simple Flexbox Layout Website',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},
		{
			types: ['normal-content-project', 'extra-url-after-name'],
			extraUrlAfterName: 'frontend/build',
			name: 'smartbrain-face-recognition',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript', 'Node.js'],
				libraries: [],
				frameworks: ['React'],
				APIs: ['Clarifai'],
			},
		},
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});

UdemyContent.list.push({
	types: ['no-content-course'],
	name: '',
	info: '',
	classes: 'spinningBackground1',
	list: [
		{
			types: ['no-content-project'],
			name: '',
			info: '',
			fileName: 'index',
			fileExtension: 'html',
			difficulty: '',
			tech: {
				languages: ['HTML', 'CSS', 'JavaScript'],
				libraries: [],
				frameworks: [],
				APIs: [],
			},
		},

		// Inner List End
	],
});
